//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryReader.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://who/", ConfigurationName="ServiceReference.PeopleStoreSoap")]
    public interface PeopleStoreSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPeopleByQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DirectoryReader.ServiceReference.Person[] FindPeopleByQuery(string query, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPeopleByQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<DirectoryReader.ServiceReference.Person[]> FindPeopleByQueryAsync(string query, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPeopleByFuzzy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DirectoryReader.ServiceReference.Person[] FindPeopleByFuzzy(string fuzzy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPeopleByFuzzy", ReplyAction="*")]
        System.Threading.Tasks.Task<DirectoryReader.ServiceReference.Person[]> FindPeopleByFuzzyAsync(string fuzzy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPersonByAlias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DirectoryReader.ServiceReference.Person FindPersonByAlias(string alias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPersonByAlias", ReplyAction="*")]
        System.Threading.Tasks.Task<DirectoryReader.ServiceReference.Person> FindPersonByAliasAsync(string alias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPeopleByAlias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DirectoryReader.ServiceReference.Person[] FindPeopleByAlias(string[] aliases);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPeopleByAlias", ReplyAction="*")]
        System.Threading.Tasks.Task<DirectoryReader.ServiceReference.Person[]> FindPeopleByAliasAsync(string[] aliases);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPeopleByEmployeeId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DirectoryReader.ServiceReference.Person[] FindPeopleByEmployeeId(int[] employeeIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPeopleByEmployeeId", ReplyAction="*")]
        System.Threading.Tasks.Task<DirectoryReader.ServiceReference.Person[]> FindPeopleByEmployeeIdAsync(int[] employeeIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPersonContextWithPeers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DirectoryReader.ServiceReference.PersonContextWithPeers FindPersonContextWithPeers(string alias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPersonContextWithPeers", ReplyAction="*")]
        System.Threading.Tasks.Task<DirectoryReader.ServiceReference.PersonContextWithPeers> FindPersonContextWithPeersAsync(string alias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPersonContextByAlias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DirectoryReader.ServiceReference.PersonContext FindPersonContextByAlias(string alias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/FindPersonContextByAlias", ReplyAction="*")]
        System.Threading.Tasks.Task<DirectoryReader.ServiceReference.PersonContext> FindPersonContextByAliasAsync(string alias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/GetTagCompletions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetTagCompletions(string prefixText, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/GetTagCompletions", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetTagCompletionsAsync(string prefixText, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/GetUnder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DirectoryReader.ServiceReference.Person[] GetUnder(string alias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/GetUnder", ReplyAction="*")]
        System.Threading.Tasks.Task<DirectoryReader.ServiceReference.Person[]> GetUnderAsync(string alias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/GetSearchCompletions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetSearchCompletions(string prefixText, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/GetSearchCompletions", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetSearchCompletionsAsync(string prefixText, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/GetSearchCompletionsByAlias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetSearchCompletionsByAlias(string prefixText, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/GetSearchCompletionsByAlias", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetSearchCompletionsByAliasAsync(string prefixText, int count);
        
        // CODEGEN: Generating message contract since message part namespace (http://schemas.microsoft.com/Search/2008/suggestions) does not match the default value (http://who/)
        [System.ServiceModel.OperationContractAttribute(Action="http://who/GetSearchAddinCompletions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DirectoryReader.ServiceReference.GetSearchAddinCompletionsResponse GetSearchAddinCompletions(DirectoryReader.ServiceReference.GetSearchAddinCompletionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://who/GetSearchAddinCompletions", ReplyAction="*")]
        System.Threading.Tasks.Task<DirectoryReader.ServiceReference.GetSearchAddinCompletionsResponse> GetSearchAddinCompletionsAsync(DirectoryReader.ServiceReference.GetSearchAddinCompletionsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://who/")]
    public partial class Person : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int positionNumberField;
        
        private string requestionIdField;
        
        private int managerPositionNumberField;
        
        private string approvedIndField;
        
        private string openPositionSubGroupCodeField;
        
        private bool isPartOfOrgTreeField;
        
        private string nameField;
        
        private string aliasField;
        
        private string samAccountNameField;
        
        private string titleField;
        
        private string officeField;
        
        private string telephoneField;
        
        private string departmentField;
        
        private int orgDepthField;
        
        private int fullTimeReportsField;
        
        private int vendorReportsField;
        
        private int employeeIdField;
        
        private System.Nullable<int> managerEmployeeIdField;
        
        private bool managerEmployeeIdFieldSpecified;
        
        private bool openPositionVendorField;
        
        private bool openPositionInternField;
        
        private string managerFullNameField;
        
        private int agencyTempReportsField;
        
        private int vendorWorkerReportsField;
        
        private int businessGuestReportsField;
        
        private int internReportsField;
        
        private int jointVentureReportsField;
        
        private int openEmployeeReportsField;
        
        private int openInternReportsField;
        
        private string imageLinkField;
        
        private string personLinkField;
        
        private string organizationLinkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PositionNumber {
            get {
                return this.positionNumberField;
            }
            set {
                this.positionNumberField = value;
                this.RaisePropertyChanged("PositionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RequestionId {
            get {
                return this.requestionIdField;
            }
            set {
                this.requestionIdField = value;
                this.RaisePropertyChanged("RequestionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ManagerPositionNumber {
            get {
                return this.managerPositionNumberField;
            }
            set {
                this.managerPositionNumberField = value;
                this.RaisePropertyChanged("ManagerPositionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ApprovedInd {
            get {
                return this.approvedIndField;
            }
            set {
                this.approvedIndField = value;
                this.RaisePropertyChanged("ApprovedInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OpenPositionSubGroupCode {
            get {
                return this.openPositionSubGroupCodeField;
            }
            set {
                this.openPositionSubGroupCodeField = value;
                this.RaisePropertyChanged("OpenPositionSubGroupCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsPartOfOrgTree {
            get {
                return this.isPartOfOrgTreeField;
            }
            set {
                this.isPartOfOrgTreeField = value;
                this.RaisePropertyChanged("IsPartOfOrgTree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("Alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SamAccountName {
            get {
                return this.samAccountNameField;
            }
            set {
                this.samAccountNameField = value;
                this.RaisePropertyChanged("SamAccountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Office {
            get {
                return this.officeField;
            }
            set {
                this.officeField = value;
                this.RaisePropertyChanged("Office");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
                this.RaisePropertyChanged("Telephone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int OrgDepth {
            get {
                return this.orgDepthField;
            }
            set {
                this.orgDepthField = value;
                this.RaisePropertyChanged("OrgDepth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int FullTimeReports {
            get {
                return this.fullTimeReportsField;
            }
            set {
                this.fullTimeReportsField = value;
                this.RaisePropertyChanged("FullTimeReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int VendorReports {
            get {
                return this.vendorReportsField;
            }
            set {
                this.vendorReportsField = value;
                this.RaisePropertyChanged("VendorReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int EmployeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
                this.RaisePropertyChanged("EmployeeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<int> ManagerEmployeeId {
            get {
                return this.managerEmployeeIdField;
            }
            set {
                this.managerEmployeeIdField = value;
                this.RaisePropertyChanged("ManagerEmployeeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ManagerEmployeeIdSpecified {
            get {
                return this.managerEmployeeIdFieldSpecified;
            }
            set {
                this.managerEmployeeIdFieldSpecified = value;
                this.RaisePropertyChanged("ManagerEmployeeIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool OpenPositionVendor {
            get {
                return this.openPositionVendorField;
            }
            set {
                this.openPositionVendorField = value;
                this.RaisePropertyChanged("OpenPositionVendor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool OpenPositionIntern {
            get {
                return this.openPositionInternField;
            }
            set {
                this.openPositionInternField = value;
                this.RaisePropertyChanged("OpenPositionIntern");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ManagerFullName {
            get {
                return this.managerFullNameField;
            }
            set {
                this.managerFullNameField = value;
                this.RaisePropertyChanged("ManagerFullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int AgencyTempReports {
            get {
                return this.agencyTempReportsField;
            }
            set {
                this.agencyTempReportsField = value;
                this.RaisePropertyChanged("AgencyTempReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int VendorWorkerReports {
            get {
                return this.vendorWorkerReportsField;
            }
            set {
                this.vendorWorkerReportsField = value;
                this.RaisePropertyChanged("VendorWorkerReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int BusinessGuestReports {
            get {
                return this.businessGuestReportsField;
            }
            set {
                this.businessGuestReportsField = value;
                this.RaisePropertyChanged("BusinessGuestReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int InternReports {
            get {
                return this.internReportsField;
            }
            set {
                this.internReportsField = value;
                this.RaisePropertyChanged("InternReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int JointVentureReports {
            get {
                return this.jointVentureReportsField;
            }
            set {
                this.jointVentureReportsField = value;
                this.RaisePropertyChanged("JointVentureReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int OpenEmployeeReports {
            get {
                return this.openEmployeeReportsField;
            }
            set {
                this.openEmployeeReportsField = value;
                this.RaisePropertyChanged("OpenEmployeeReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int OpenInternReports {
            get {
                return this.openInternReportsField;
            }
            set {
                this.openInternReportsField = value;
                this.RaisePropertyChanged("OpenInternReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string ImageLink {
            get {
                return this.imageLinkField;
            }
            set {
                this.imageLinkField = value;
                this.RaisePropertyChanged("ImageLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string PersonLink {
            get {
                return this.personLinkField;
            }
            set {
                this.personLinkField = value;
                this.RaisePropertyChanged("PersonLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string OrganizationLink {
            get {
                return this.organizationLinkField;
            }
            set {
                this.organizationLinkField = value;
                this.RaisePropertyChanged("OrganizationLink");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/Search/2008/suggestions")]
    public partial class Image : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sourceField;
        
        private string widthField;
        
        private string heightField;
        
        private string alignField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string align {
            get {
                return this.alignField;
            }
            set {
                this.alignField = value;
                this.RaisePropertyChanged("align");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/Search/2008/suggestions")]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string textField;
        
        private string descriptionField;
        
        private Image imageField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Image Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("Image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/Search/2008/suggestions")]
    public partial class SearchSuggestion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string queryField;
        
        private Item[] sectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("Query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Item[] Section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
                this.RaisePropertyChanged("Section");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://who/")]
    public partial class DirectData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fullNameField;
        
        private string titleField;
        
        private int employeeIdField;
        
        private string officeField;
        
        private string locationField;
        
        private bool vendorField;
        
        private System.Nullable<int> totalReportsField;
        
        private System.Nullable<int> totalOpenReportsField;
        
        private int nestedSetLeftField;
        
        private int nestedSetRightField;
        
        private byte treeDepthField;
        
        private string aliasField;
        
        private int positionNumberField;
        
        private string requisitionAliasField;
        
        private int fullTimeReportsField;
        
        private bool agencyTempField;
        
        private bool vendorWorkerField;
        
        private bool businessGuestField;
        
        private bool internField;
        
        private bool jointVentureEmpField;
        
        private string departmentField;
        
        private string deptNicknameField;
        
        private string keywordsField;
        
        private string ownedDLsField;
        
        private string tagsListField;
        
        private int pMRollupCountField;
        
        private int devRollupCountField;
        
        private int testRollupCountField;
        
        private int otherRollupCountField;
        
        private System.Nullable<bool> isOpenPositionField;
        
        private string approvedIndField;
        
        private string imageLinkField;
        
        private string personLinkField;
        
        private string organizationLinkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int EmployeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
                this.RaisePropertyChanged("EmployeeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Office {
            get {
                return this.officeField;
            }
            set {
                this.officeField = value;
                this.RaisePropertyChanged("Office");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Vendor {
            get {
                return this.vendorField;
            }
            set {
                this.vendorField = value;
                this.RaisePropertyChanged("Vendor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> TotalReports {
            get {
                return this.totalReportsField;
            }
            set {
                this.totalReportsField = value;
                this.RaisePropertyChanged("TotalReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> TotalOpenReports {
            get {
                return this.totalOpenReportsField;
            }
            set {
                this.totalOpenReportsField = value;
                this.RaisePropertyChanged("TotalOpenReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int NestedSetLeft {
            get {
                return this.nestedSetLeftField;
            }
            set {
                this.nestedSetLeftField = value;
                this.RaisePropertyChanged("NestedSetLeft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int NestedSetRight {
            get {
                return this.nestedSetRightField;
            }
            set {
                this.nestedSetRightField = value;
                this.RaisePropertyChanged("NestedSetRight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public byte TreeDepth {
            get {
                return this.treeDepthField;
            }
            set {
                this.treeDepthField = value;
                this.RaisePropertyChanged("TreeDepth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("Alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int PositionNumber {
            get {
                return this.positionNumberField;
            }
            set {
                this.positionNumberField = value;
                this.RaisePropertyChanged("PositionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string RequisitionAlias {
            get {
                return this.requisitionAliasField;
            }
            set {
                this.requisitionAliasField = value;
                this.RaisePropertyChanged("RequisitionAlias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int FullTimeReports {
            get {
                return this.fullTimeReportsField;
            }
            set {
                this.fullTimeReportsField = value;
                this.RaisePropertyChanged("FullTimeReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool AgencyTemp {
            get {
                return this.agencyTempField;
            }
            set {
                this.agencyTempField = value;
                this.RaisePropertyChanged("AgencyTemp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool VendorWorker {
            get {
                return this.vendorWorkerField;
            }
            set {
                this.vendorWorkerField = value;
                this.RaisePropertyChanged("VendorWorker");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool BusinessGuest {
            get {
                return this.businessGuestField;
            }
            set {
                this.businessGuestField = value;
                this.RaisePropertyChanged("BusinessGuest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool Intern {
            get {
                return this.internField;
            }
            set {
                this.internField = value;
                this.RaisePropertyChanged("Intern");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool JointVentureEmp {
            get {
                return this.jointVentureEmpField;
            }
            set {
                this.jointVentureEmpField = value;
                this.RaisePropertyChanged("JointVentureEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string DeptNickname {
            get {
                return this.deptNicknameField;
            }
            set {
                this.deptNicknameField = value;
                this.RaisePropertyChanged("DeptNickname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
                this.RaisePropertyChanged("Keywords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string OwnedDLs {
            get {
                return this.ownedDLsField;
            }
            set {
                this.ownedDLsField = value;
                this.RaisePropertyChanged("OwnedDLs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string TagsList {
            get {
                return this.tagsListField;
            }
            set {
                this.tagsListField = value;
                this.RaisePropertyChanged("TagsList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int PMRollupCount {
            get {
                return this.pMRollupCountField;
            }
            set {
                this.pMRollupCountField = value;
                this.RaisePropertyChanged("PMRollupCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int DevRollupCount {
            get {
                return this.devRollupCountField;
            }
            set {
                this.devRollupCountField = value;
                this.RaisePropertyChanged("DevRollupCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int TestRollupCount {
            get {
                return this.testRollupCountField;
            }
            set {
                this.testRollupCountField = value;
                this.RaisePropertyChanged("TestRollupCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int OtherRollupCount {
            get {
                return this.otherRollupCountField;
            }
            set {
                this.otherRollupCountField = value;
                this.RaisePropertyChanged("OtherRollupCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<bool> IsOpenPosition {
            get {
                return this.isOpenPositionField;
            }
            set {
                this.isOpenPositionField = value;
                this.RaisePropertyChanged("IsOpenPosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string ApprovedInd {
            get {
                return this.approvedIndField;
            }
            set {
                this.approvedIndField = value;
                this.RaisePropertyChanged("ApprovedInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string ImageLink {
            get {
                return this.imageLinkField;
            }
            set {
                this.imageLinkField = value;
                this.RaisePropertyChanged("ImageLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string PersonLink {
            get {
                return this.personLinkField;
            }
            set {
                this.personLinkField = value;
                this.RaisePropertyChanged("PersonLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string OrganizationLink {
            get {
                return this.organizationLinkField;
            }
            set {
                this.organizationLinkField = value;
                this.RaisePropertyChanged("OrganizationLink");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://who/")]
    public partial class DirectsChain : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DirectData managerField;
        
        private DirectData[] directsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DirectData Manager {
            get {
                return this.managerField;
            }
            set {
                this.managerField = value;
                this.RaisePropertyChanged("Manager");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public DirectData[] Directs {
            get {
                return this.directsField;
            }
            set {
                this.directsField = value;
                this.RaisePropertyChanged("Directs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonContextWithPeers))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://who/")]
    public partial class PersonContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Person personField;
        
        private Person[] managersField;
        
        private DirectsChain[] directsChainsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Person Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
                this.RaisePropertyChanged("Person");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Person[] Managers {
            get {
                return this.managersField;
            }
            set {
                this.managersField = value;
                this.RaisePropertyChanged("Managers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public DirectsChain[] DirectsChains {
            get {
                return this.directsChainsField;
            }
            set {
                this.directsChainsField = value;
                this.RaisePropertyChanged("DirectsChains");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://who/")]
    public partial class PersonContextWithPeers : PersonContext {
        
        private DirectData[] peersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public DirectData[] Peers {
            get {
                return this.peersField;
            }
            set {
                this.peersField = value;
                this.RaisePropertyChanged("Peers");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSearchAddinCompletions", WrapperNamespace="http://who/", IsWrapped=true)]
    public partial class GetSearchAddinCompletionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://who/", Order=0)]
        public string prefixText;
        
        public GetSearchAddinCompletionsRequest() {
        }
        
        public GetSearchAddinCompletionsRequest(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSearchAddinCompletionsResponse", WrapperNamespace="http://who/", IsWrapped=true)]
    public partial class GetSearchAddinCompletionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/Search/2008/suggestions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/Search/2008/suggestions", IsNullable=true)]
        public DirectoryReader.ServiceReference.SearchSuggestion GetSearchAddinCompletionsResult;
        
        public GetSearchAddinCompletionsResponse() {
        }
        
        public GetSearchAddinCompletionsResponse(DirectoryReader.ServiceReference.SearchSuggestion GetSearchAddinCompletionsResult) {
            this.GetSearchAddinCompletionsResult = GetSearchAddinCompletionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PeopleStoreSoapChannel : DirectoryReader.ServiceReference.PeopleStoreSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeopleStoreSoapClient : System.ServiceModel.ClientBase<DirectoryReader.ServiceReference.PeopleStoreSoap>, DirectoryReader.ServiceReference.PeopleStoreSoap {
        
        public PeopleStoreSoapClient() {
        }
        
        public PeopleStoreSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeopleStoreSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleStoreSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleStoreSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DirectoryReader.ServiceReference.Person[] FindPeopleByQuery(string query, int count) {
            return base.Channel.FindPeopleByQuery(query, count);
        }
        
        public System.Threading.Tasks.Task<DirectoryReader.ServiceReference.Person[]> FindPeopleByQueryAsync(string query, int count) {
            return base.Channel.FindPeopleByQueryAsync(query, count);
        }
        
        public DirectoryReader.ServiceReference.Person[] FindPeopleByFuzzy(string fuzzy) {
            return base.Channel.FindPeopleByFuzzy(fuzzy);
        }
        
        public System.Threading.Tasks.Task<DirectoryReader.ServiceReference.Person[]> FindPeopleByFuzzyAsync(string fuzzy) {
            return base.Channel.FindPeopleByFuzzyAsync(fuzzy);
        }
        
        public DirectoryReader.ServiceReference.Person FindPersonByAlias(string alias) {
            return base.Channel.FindPersonByAlias(alias);
        }
        
        public System.Threading.Tasks.Task<DirectoryReader.ServiceReference.Person> FindPersonByAliasAsync(string alias) {
            return base.Channel.FindPersonByAliasAsync(alias);
        }
        
        public DirectoryReader.ServiceReference.Person[] FindPeopleByAlias(string[] aliases) {
            return base.Channel.FindPeopleByAlias(aliases);
        }
        
        public System.Threading.Tasks.Task<DirectoryReader.ServiceReference.Person[]> FindPeopleByAliasAsync(string[] aliases) {
            return base.Channel.FindPeopleByAliasAsync(aliases);
        }
        
        public DirectoryReader.ServiceReference.Person[] FindPeopleByEmployeeId(int[] employeeIds) {
            return base.Channel.FindPeopleByEmployeeId(employeeIds);
        }
        
        public System.Threading.Tasks.Task<DirectoryReader.ServiceReference.Person[]> FindPeopleByEmployeeIdAsync(int[] employeeIds) {
            return base.Channel.FindPeopleByEmployeeIdAsync(employeeIds);
        }
        
        public DirectoryReader.ServiceReference.PersonContextWithPeers FindPersonContextWithPeers(string alias) {
            return base.Channel.FindPersonContextWithPeers(alias);
        }
        
        public System.Threading.Tasks.Task<DirectoryReader.ServiceReference.PersonContextWithPeers> FindPersonContextWithPeersAsync(string alias) {
            return base.Channel.FindPersonContextWithPeersAsync(alias);
        }
        
        public DirectoryReader.ServiceReference.PersonContext FindPersonContextByAlias(string alias) {
            return base.Channel.FindPersonContextByAlias(alias);
        }
        
        public System.Threading.Tasks.Task<DirectoryReader.ServiceReference.PersonContext> FindPersonContextByAliasAsync(string alias) {
            return base.Channel.FindPersonContextByAliasAsync(alias);
        }
        
        public string[] GetTagCompletions(string prefixText, int count) {
            return base.Channel.GetTagCompletions(prefixText, count);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTagCompletionsAsync(string prefixText, int count) {
            return base.Channel.GetTagCompletionsAsync(prefixText, count);
        }
        
        public DirectoryReader.ServiceReference.Person[] GetUnder(string alias) {
            return base.Channel.GetUnder(alias);
        }
        
        public System.Threading.Tasks.Task<DirectoryReader.ServiceReference.Person[]> GetUnderAsync(string alias) {
            return base.Channel.GetUnderAsync(alias);
        }
        
        public string[] GetSearchCompletions(string prefixText, int count) {
            return base.Channel.GetSearchCompletions(prefixText, count);
        }
        
        public System.Threading.Tasks.Task<string[]> GetSearchCompletionsAsync(string prefixText, int count) {
            return base.Channel.GetSearchCompletionsAsync(prefixText, count);
        }
        
        public string[] GetSearchCompletionsByAlias(string prefixText, int count) {
            return base.Channel.GetSearchCompletionsByAlias(prefixText, count);
        }
        
        public System.Threading.Tasks.Task<string[]> GetSearchCompletionsByAliasAsync(string prefixText, int count) {
            return base.Channel.GetSearchCompletionsByAliasAsync(prefixText, count);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DirectoryReader.ServiceReference.GetSearchAddinCompletionsResponse DirectoryReader.ServiceReference.PeopleStoreSoap.GetSearchAddinCompletions(DirectoryReader.ServiceReference.GetSearchAddinCompletionsRequest request) {
            return base.Channel.GetSearchAddinCompletions(request);
        }
        
        public DirectoryReader.ServiceReference.SearchSuggestion GetSearchAddinCompletions(string prefixText) {
            DirectoryReader.ServiceReference.GetSearchAddinCompletionsRequest inValue = new DirectoryReader.ServiceReference.GetSearchAddinCompletionsRequest();
            inValue.prefixText = prefixText;
            DirectoryReader.ServiceReference.GetSearchAddinCompletionsResponse retVal = ((DirectoryReader.ServiceReference.PeopleStoreSoap)(this)).GetSearchAddinCompletions(inValue);
            return retVal.GetSearchAddinCompletionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DirectoryReader.ServiceReference.GetSearchAddinCompletionsResponse> DirectoryReader.ServiceReference.PeopleStoreSoap.GetSearchAddinCompletionsAsync(DirectoryReader.ServiceReference.GetSearchAddinCompletionsRequest request) {
            return base.Channel.GetSearchAddinCompletionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DirectoryReader.ServiceReference.GetSearchAddinCompletionsResponse> GetSearchAddinCompletionsAsync(string prefixText) {
            DirectoryReader.ServiceReference.GetSearchAddinCompletionsRequest inValue = new DirectoryReader.ServiceReference.GetSearchAddinCompletionsRequest();
            inValue.prefixText = prefixText;
            return ((DirectoryReader.ServiceReference.PeopleStoreSoap)(this)).GetSearchAddinCompletionsAsync(inValue);
        }
    }
}
